<?php
// Quick test runner for emifree_handle_contact_submit
// Run: php tests/contact-test.php

// Bootstrap WP
require_once __DIR__ . '/../../../wp-load.php';

// Build POST payload matching the form
$_POST = array(
    'emifree_contact_nonce' => wp_create_nonce( 'emifree_contact' ),
    'name'    => 'Test User',
    'email'   => 'test@example.com',
    'company' => 'Acme Inc',
    'message' => 'This is a test message generated by the unit test.',
);

// Capture output
ob_start();

// Call the handler directly
emifree_handle_contact_submit();

$out = ob_get_clean();
file_put_contents(__DIR__ . '/contact-test-output.json', $out);

echo "Response written to tests/contact-test-output.json\n";
echo $out . "\n";
